/**
 * Tests for mcp-prusaslicer.
 *
 * Tests requiring prusa-slicer are guarded by an environment variable:
 *   PRUSASLICER_RUN_NATIVE=1  — enable integration tests against the real slicer.
 *
 * Unit tests (parsePrusaTime, production G-code parser, schema invariants, MCP
 * wire, input validation) run without any guard and require no subprocess.
 *
 * Reference values for tests/fixtures/cube_20mm_pla.gcode
 * (PrusaSlicer 2.9.2, aarch64 Debian trixie, cube_20mm.stl + pla_0.4_0.2.ini):
 *   filament used [mm]  = 1487.15   → filament_length_mm  = 1487.15
 *   filament used [cm3] = 3.58      → filament_volume_mm3 = 3580
 *   filament used [g]   = 4.44      → filament_mass_g     = 4.44
 *   estimated printing time (normal mode) = 19m 50s → print_time_s = 1190
 *   estimated printing time (silent mode) = 20m 40s
 */

import { assert, assertEquals, assertRejects, assertThrows } from "@std/assert";
import denoConfig from "../deno.json" with { type: "json" };
import {
  collectAppliedOverrides,
  parseGcodeStats,
  parsePrusaTime,
  sliceFff,
  SlicingError,
} from "../src/api/prusa-slicer.ts";
import {
  assertAdmittedStlSource,
  InputArtifactError,
} from "../src/api/input-artifact.ts";
import { allTools } from "../src/tools/mod.ts";
import { createSlicerServer, parseCli } from "../server.ts";

const RUN_NATIVE = Deno.env.get("PRUSASLICER_RUN_NATIVE") === "1";

// Fixture paths — used in both unit and native tests.
const CUBE_10MM_STL = new URL("./fixtures/cube.stl", import.meta.url).pathname;
const CUBE_20MM_STL = new URL("./fixtures/cube_20mm.stl", import.meta.url).pathname;
const PROFILE_INI = new URL("./fixtures/pla_0.4_0.2.ini", import.meta.url).pathname;
const GCODE_FIXTURE = new URL(
  "./fixtures/cube_20mm_pla.gcode",
  import.meta.url,
).pathname;

// ---------------------------------------------------------------------------
// parsePrusaTime — pure unit tests, no subprocess
// ---------------------------------------------------------------------------

Deno.test("parsePrusaTime converts '19m 50s' to 1190 seconds", () => {
  assertEquals(parsePrusaTime("19m 50s"), 1190);
});

Deno.test("parsePrusaTime converts '12m 45s' to 765 seconds", () => {
  assertEquals(parsePrusaTime("12m 45s"), 765);
});

Deno.test("parsePrusaTime converts '1h 2m 30s' to 3750 seconds", () => {
  assertEquals(parsePrusaTime("1h 2m 30s"), 3750);
});

Deno.test("parsePrusaTime converts '45s' to 45 seconds", () => {
  assertEquals(parsePrusaTime("45s"), 45);
});

Deno.test("parsePrusaTime converts '2h' to 7200 seconds", () => {
  assertEquals(parsePrusaTime("2h"), 7200);
});

Deno.test("parsePrusaTime converts '5m' to 300 seconds", () => {
  assertEquals(parsePrusaTime("5m"), 300);
});

Deno.test("parsePrusaTime returns null for empty string", () => {
  assertEquals(parsePrusaTime(""), null);
});

Deno.test("parsePrusaTime converts '20m 40s' (silent mode) to 1240 seconds", () => {
  assertEquals(parsePrusaTime("20m 40s"), 1240);
});

// ---------------------------------------------------------------------------
// Production G-code parser — unit tests against committed real G-code stats
// (no subprocess, no prusa-slicer required)
// ---------------------------------------------------------------------------

function estimateTool() {
  const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
  assert(tool, "tool must exist");
  return tool;
}

function minimalGcode(options: {
  header?: string;
  config?: string;
  includeConfig?: boolean;
}): string {
  const header = options.header ??
    "; generated by PrusaSlicer 2.9.2 on 2026-08-05 at 00:09:06 UTC";
  const configLines = options.includeConfig === false ? [] : [
    "; prusaslicer_config = begin",
    options.config ?? "; layer_height = 0.2",
    "; prusaslicer_config = end",
  ];
  return [
    header,
    "; filament used [mm] = 1.00",
    "; filament used [cm3] = 0.01",
    "; filament used [g] = 0.01",
    "; estimated printing time (normal mode) = 1s",
    "; estimated printing time (silent mode) = 2s",
    ...configLines,
    "",
  ].join("\n");
}

async function sha256HexOf(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, "0"))
    .join("");
}

Deno.test(
  "parseGcodeStats from cube_20mm_pla.gcode matches committed stats and engine",
  async () => {
    const gcode = await Deno.readTextFile(GCODE_FIXTURE);
    const stats = await parseGcodeStats(gcode);
    assertEquals(stats.filament_length_mm, 1487.15);
    assertEquals(stats.filament_volume_mm3, 3580);
    assertEquals(stats.filament_mass_g, 4.44);
    assertEquals(stats.print_time_s, 1190);
    assertEquals(stats.print_time_normal_mode, "19m 50s");
    assertEquals(stats.print_time_silent_mode, "20m 40s");
    assertEquals(stats.engine_name, "PrusaSlicer");
    assertEquals(stats.engine_version, "2.9.2");
  },
);

Deno.test(
  "parseGcodeStats hashes the exact emitted prusaslicer_config block",
  async () => {
    const gcode = await Deno.readTextFile(GCODE_FIXTURE);
    const stats = await parseGcodeStats(gcode);
    const beginMarker = "; prusaslicer_config = begin";
    const endMarker = "; prusaslicer_config = end";
    const beginIdx = gcode.indexOf(beginMarker);
    const endIdx = gcode.indexOf(endMarker, beginIdx);
    assert(beginIdx >= 0 && endIdx > beginIdx, "fixture must contain config markers");
    const block = gcode.slice(beginIdx, endIdx + endMarker.length);
    assertEquals(stats.effective_config_sha256, await sha256HexOf(block));
    assertEquals(stats.effective_config_sha256.length, 64);
  },
);

Deno.test(
  "parseGcodeStats returns a bounded raw effective-config summary tied to its hash",
  async () => {
    const stats = await parseGcodeStats(minimalGcode({
      config: [
        "; printer_technology = FFF",
        "; nozzle_diameter = 0.4,0.4",
        "; layer_height = 0.2",
        "; first_layer_height = 0.2",
        "; fill_density = 20%",
        "; fill_pattern = gyroid",
        "; perimeters = 3",
        "; top_solid_layers = 5",
        "; bottom_solid_layers = 4",
        "; support_material = 0",
        "; support_material_auto = 0",
        "; filament_diameter = 1.75",
        "; filament_density = 1.24",
        "; gcode_flavor = marlin",
      ].join("\n"),
    }));

    assertEquals(
      stats.effective_config_summary.config_sha256,
      stats.effective_config_sha256,
    );
    assertEquals(stats.effective_config_summary.values, {
      printer_technology: "FFF",
      nozzle_diameter: "0.4,0.4",
      layer_height: "0.2",
      first_layer_height: "0.2",
      fill_density: "20%",
      fill_pattern: "gyroid",
      perimeters: "3",
      top_solid_layers: "5",
      bottom_solid_layers: "4",
      support_material: "0",
      support_material_auto: "0",
      filament_diameter: "1.75",
      filament_density: "1.24",
      gcode_flavor: "marlin",
    });
  },
);

Deno.test("parseGcodeStats leaves absent selected config keys null without defaults", async () => {
  const stats = await parseGcodeStats(minimalGcode({
    config: "; layer_height = 0.2",
  }));
  assertEquals(stats.effective_config_summary.values.layer_height, "0.2");
  assertEquals(stats.effective_config_summary.values.fill_pattern, null);
  assertEquals(stats.effective_config_summary.values.support_material, null);
});

Deno.test("parseGcodeStats rejects ambiguous duplicate selected config keys", async () => {
  await assertRejects(
    () =>
      parseGcodeStats(minimalGcode({
        config: "; layer_height = 0.2\n; layer_height = 0.3",
      })),
    SlicingError,
    "duplicate selected config key",
  );
});

Deno.test("parseGcodeStats reads the observed engine from the G-code header", async () => {
  const stats = await parseGcodeStats(minimalGcode({
    header: "; generated by SuperSlicer 2.5.59 on 2024-01-01 at 00:00:00 UTC",
  }));
  assertEquals(stats.engine_name, "SuperSlicer");
  assertEquals(stats.engine_version, "2.5.59");
});

Deno.test("parseGcodeStats fails closed when the generated-by header is missing", async () => {
  await assertRejects(
    () => parseGcodeStats(minimalGcode({ header: "; not a slicer header" })),
    SlicingError,
    "generated by",
  );
});

Deno.test("parseGcodeStats fails closed when prusaslicer_config is missing", async () => {
  await assertRejects(
    () => parseGcodeStats(minimalGcode({ includeConfig: false })),
    SlicingError,
    "prusaslicer_config",
  );
});

Deno.test("collectAppliedOverrides keeps only caller-provided print overrides", () => {
  assertEquals(collectAppliedOverrides({}), {});
  assertEquals(
    collectAppliedOverrides({ layerHeightMm: 0.3 }),
    { layer_height_mm: 0.3 },
  );
  assertEquals(
    collectAppliedOverrides({
      layerHeightMm: 0.3,
      infillPercent: 15,
      filamentDensityGcm3: 1.24,
    }),
    {
      layer_height_mm: 0.3,
      infill_percent: 15,
      filament_density_g_cm3: 1.24,
    },
  );
  assertEquals(
    collectAppliedOverrides({
      stlPath: CUBE_20MM_STL,
      profileIniPath: PROFILE_INI,
      layerHeightMm: 0.2,
      timeoutMs: 5_000,
    }),
    { layer_height_mm: 0.2 },
  );
});

// ---------------------------------------------------------------------------
// Schema invariants
// ---------------------------------------------------------------------------

Deno.test("All slicer tools declare closed outputSchemas with required not_checked", () => {
  for (const tool of allTools) {
    const schema = tool.outputSchema as Record<string, unknown>;
    assertEquals(
      schema.additionalProperties,
      false,
      `${tool.name}: outputSchema must have additionalProperties: false`,
    );
    const required = schema.required as string[];
    assert(
      required.includes("not_checked"),
      `${tool.name}: outputSchema.required must include 'not_checked'`,
    );
    assert(
      required.includes("print_time_s"),
      `${tool.name}: outputSchema.required must include 'print_time_s'`,
    );
    assert(
      required.includes("filament_length_mm"),
      `${tool.name}: outputSchema.required must include 'filament_length_mm'`,
    );
    assert(
      required.includes("stl_artifact"),
      `${tool.name}: outputSchema.required must include 'stl_artifact'`,
    );
    assert(
      required.includes("profile_artifact"),
      `${tool.name}: outputSchema.required must include 'profile_artifact'`,
    );
    assert(
      required.includes("gcode_sha256"),
      `${tool.name}: outputSchema.required must include 'gcode_sha256'`,
    );
    assert(
      required.includes("engine_name"),
      `${tool.name}: outputSchema.required must include 'engine_name'`,
    );
    assert(
      required.includes("engine_version"),
      `${tool.name}: outputSchema.required must include 'engine_version'`,
    );
    assert(
      required.includes("effective_config_sha256"),
      `${tool.name}: outputSchema.required must include 'effective_config_sha256'`,
    );
    assert(
      required.includes("effective_config_summary"),
      `${tool.name}: outputSchema.required must include 'effective_config_summary'`,
    );
    assert(
      required.includes("overrides_applied"),
      `${tool.name}: outputSchema.required must include 'overrides_applied'`,
    );
  }
});

Deno.test("effective_config_summary outputSchema is closed and bounded", () => {
  const schema = estimateTool().outputSchema as Record<string, unknown>;
  const properties = schema.properties as Record<string, Record<string, unknown>>;
  const summary = properties.effective_config_summary;
  assertEquals(summary.type, "object");
  assertEquals(summary.additionalProperties, false);
  assertEquals(summary.required, ["config_sha256", "values"]);
  const values = (summary.properties as Record<string, Record<string, unknown>>).values;
  assertEquals(values.type, "object");
  assertEquals(values.additionalProperties, false);
  assertEquals(values.required, [
    "printer_technology",
    "nozzle_diameter",
    "layer_height",
    "first_layer_height",
    "fill_density",
    "fill_pattern",
    "perimeters",
    "top_solid_layers",
    "bottom_solid_layers",
    "support_material",
    "support_material_auto",
    "filament_diameter",
    "filament_density",
    "gcode_flavor",
  ]);
});

Deno.test("timeout_ms JSON Schema is a positive integer", () => {
  const schema = estimateTool().inputSchema as Record<string, unknown>;
  const properties = schema.properties as Record<string, Record<string, unknown>>;
  const timeout = properties.timeout_ms;
  assertEquals(timeout.type, "integer");
  assertEquals(timeout.minimum, 1);
});

Deno.test("overrides_applied outputSchema is a closed object of print overrides", () => {
  const schema = estimateTool().outputSchema as Record<string, unknown>;
  const properties = schema.properties as Record<string, Record<string, unknown>>;
  const overrides = properties.overrides_applied;
  assertEquals(overrides.type, "object");
  assertEquals(overrides.additionalProperties, false);
  const overrideProps = overrides.properties as Record<string, unknown>;
  assertEquals(Object.keys(overrideProps).sort(), [
    "filament_density_g_cm3",
    "infill_percent",
    "layer_height_mm",
  ]);
});

Deno.test("filament_mass_g is NOT required in outputSchema (absent when no density)", () => {
  for (const tool of allTools) {
    const schema = tool.outputSchema as Record<string, unknown>;
    const required = schema.required as string[];
    assert(
      !required.includes("filament_mass_g"),
      `${tool.name}: filament_mass_g must not be in required (absent, not null, when no density)`,
    );
  }
});

Deno.test("All slicer tools declare openWorldHint=false and destructiveHint=false", () => {
  for (const tool of allTools) {
    const ann = tool.annotations;
    assertEquals(ann.openWorldHint, false, `${tool.name}: openWorldHint must be false`);
    assertEquals(
      ann.destructiveHint,
      false,
      `${tool.name}: destructiveHint must be false`,
    );
  }
});

Deno.test("JSR and image publication remain gated on the qualified native suite", async () => {
  const publishWorkflow = await Deno.readTextFile(
    new URL("../.github/workflows/publish.yml", import.meta.url),
  );
  const dockerWorkflow = await Deno.readTextFile(
    new URL("../.github/workflows/docker.yml", import.meta.url),
  );
  for (const workflow of [publishWorkflow, dockerWorkflow]) {
    assert(
      workflow.includes("prusa-slicer=2.9.2+dfsg-1"),
      "each release gate must install the qualified PrusaSlicer package exactly",
    );
    assert(
      workflow.includes("PRUSASLICER_RUN_NATIVE=1 deno task release:check"),
      "each release gate must run native slicer tests before publication",
    );
  }
  assert(
    /publish-jsr:\s+needs: check/.test(publishWorkflow),
    "JSR publication must depend on the native release gate",
  );
  assert(
    /build-push:\s+needs: native-check/.test(dockerWorkflow),
    "image publication must depend on the native release gate",
  );
  assert(
    dockerWorkflow.includes('test "$GITHUB_REF_NAME" = "$expected_tag"'),
    "a release image tag must match the package version",
  );
});

// ---------------------------------------------------------------------------
// CLI transport selection
// ---------------------------------------------------------------------------

Deno.test("--stdio selects native stdio without HTTP flags", () => {
  assertEquals(parseCli(["--stdio"]).transport, "stdio");
});

Deno.test("--stdio rejects HTTP flags in either order", () => {
  for (
    const args of [
      ["--stdio", "--port=3022"],
      ["--port", "3022", "--stdio"],
      ["--stdio", "--hostname=0.0.0.0"],
      ["--hostname", "0.0.0.0", "--stdio"],
    ]
  ) {
    assertThrows(() => parseCli(args), TypeError, "--stdio cannot be combined");
  }
});

// ---------------------------------------------------------------------------
// MCP wire contract
// ---------------------------------------------------------------------------

const PROTOCOL_VERSION = "2026-07-28";

async function rpc(
  url: string,
  method: string,
  params: Record<string, unknown> = {},
): Promise<{ response: Response; body: { result: unknown } }> {
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "mcp-protocol-version": PROTOCOL_VERSION,
      "mcp-method": method,
      ...(method === "tools/call" && typeof params.name === "string"
        ? { "mcp-name": params.name }
        : {}),
    },
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 1,
      method,
      params: {
        ...params,
        _meta: {
          "io.modelcontextprotocol/protocolVersion": PROTOCOL_VERSION,
          "io.modelcontextprotocol/clientCapabilities": {},
          "io.modelcontextprotocol/clientInfo": {
            name: "mcp-prusaslicer-test",
            version: "0.1.0",
          },
        },
      },
    }),
  });
  const body = await response.json();
  return { response, body };
}

function freePort(): number {
  return 13022 + Math.floor(Math.random() * 100);
}

Deno.test("Slicer server starts and serves stateless MCP server/discover", async () => {
  const { app } = createSlicerServer({ logger: () => {} });
  const port = freePort();
  const http = await app.startHttp({
    port,
    hostname: "127.0.0.1",
    onListen: () => {},
  });
  const url = `http://127.0.0.1:${port}/mcp`;
  try {
    const { response, body } = await rpc(url, "server/discover");
    // Stateless transport: no session ID.
    assertEquals(response.headers.get("mcp-session-id"), null);
    const result = body.result as Record<string, unknown>;
    const serverInfo = result.serverInfo as Record<string, unknown>;
    assertEquals(serverInfo.name, "mcp-prusaslicer");
    assertEquals(
      serverInfo.version,
      denoConfig.version,
      "server/discover version must match the package manifest",
    );
  } finally {
    await http.shutdown();
  }
});

Deno.test("Slicer server lists prusaslicer_estimate_fff in tools/list", async () => {
  const { app } = createSlicerServer({ logger: () => {} });
  const port = freePort();
  const http = await app.startHttp({
    port,
    hostname: "127.0.0.1",
    onListen: () => {},
  });
  const url = `http://127.0.0.1:${port}/mcp`;
  try {
    const { body } = await rpc(url, "tools/list");
    const result = body.result as Record<string, unknown>;
    const tools = result.tools as Array<{ name: string }>;
    assert(Array.isArray(tools), "tools must be an array");
    const names = tools.map((t) => t.name);
    assert(
      names.includes("prusaslicer_estimate_fff"),
      "must include prusaslicer_estimate_fff",
    );
    const listed = tools.find((t) => t.name === "prusaslicer_estimate_fff") as
      | Record<string, unknown>
      | undefined;
    assert(listed, "listed tools must include prusaslicer_estimate_fff");
    const inputSchema = listed.inputSchema as {
      properties: { timeout_ms: { type: string; minimum: number } };
    };
    assertEquals(inputSchema.properties.timeout_ms.type, "integer");
    assertEquals(inputSchema.properties.timeout_ms.minimum, 1);
  } finally {
    await http.shutdown();
  }
});

Deno.test("tools/call rejects non-positive timeout_ms at the JSON Schema boundary", async () => {
  const { app } = createSlicerServer({ logger: () => {} });
  const port = freePort();
  const http = await app.startHttp({
    port,
    hostname: "127.0.0.1",
    onListen: () => {},
  });
  const url = `http://127.0.0.1:${port}/mcp`;
  try {
    for (const timeout_ms of [0, 1.5]) {
      const { body } = await rpc(url, "tools/call", {
        name: "prusaslicer_estimate_fff",
        arguments: {
          stl_path: CUBE_20MM_STL,
          profile_ini_path: PROFILE_INI,
          timeout_ms,
        },
      });
      const payload = body as Record<string, unknown>;
      const err = payload.error as { message?: string } | undefined;
      const result = payload.result as { isError?: boolean } | undefined;
      const text = JSON.stringify(payload);
      assert(
        err !== undefined || result?.isError === true,
        `timeout_ms: ${timeout_ms} must be rejected, got: ${text}`,
      );
      assert(
        text.includes("timeout_ms") || text.includes(">= 1") ||
          text.includes("integer") || text.includes("Invalid arguments"),
        `schema error should describe timeout_ms, got: ${text}`,
      );
    }
  } finally {
    await http.shutdown();
  }
});

// ---------------------------------------------------------------------------
// Input validation — no subprocess required
// ---------------------------------------------------------------------------

Deno.test("prusaslicer_estimate_fff rejects missing stl_path", async () => {
  const tool = estimateTool();
  await assertRejects(
    () =>
      tool.handler({
        profile_ini_path: PROFILE_INI,
      }) as Promise<unknown>,
    TypeError,
    "stl_path",
  );
});

Deno.test("prusaslicer_estimate_fff rejects empty stl_path", async () => {
  const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
  assert(tool, "tool must exist");
  await assertRejects(
    () =>
      tool.handler({
        stl_path: "   ",
        profile_ini_path: PROFILE_INI,
      }) as Promise<unknown>,
    TypeError,
    "stl_path",
  );
});

Deno.test("prusaslicer_estimate_fff rejects missing profile_ini_path", async () => {
  const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
  assert(tool, "tool must exist");
  await assertRejects(
    () =>
      tool.handler({
        stl_path: "/tmp/x.stl",
      }) as Promise<unknown>,
    TypeError,
    "profile_ini_path",
  );
});

Deno.test("prusaslicer_estimate_fff rejects invalid stl_sha256 format", async () => {
  const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
  assert(tool, "tool must exist");
  await assertRejects(
    () =>
      tool.handler({
        stl_path: "/tmp/x.stl",
        profile_ini_path: PROFILE_INI,
        stl_sha256: "not-a-sha256",
      }) as Promise<unknown>,
    Error,
    "expected_stl_sha256",
  );
});

Deno.test("prusaslicer_estimate_fff rejects invalid profile_sha256 format", async () => {
  const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
  assert(tool, "tool must exist");
  // Use a real STL so the STL snapshot succeeds; the profile hash check fires next.
  await assertRejects(
    () =>
      tool.handler({
        stl_path: CUBE_20MM_STL,
        profile_ini_path: PROFILE_INI,
        profile_sha256: "not-a-sha256",
      }) as Promise<unknown>,
    Error,
    "expected_ini_sha256",
  );
});

Deno.test("prusaslicer_estimate_fff reports STL not found as InputArtifactError", async () => {
  const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
  assert(tool, "tool must exist");
  await assertRejects(
    () =>
      tool.handler({
        stl_path: "/nonexistent/x.stl",
        profile_ini_path: PROFILE_INI,
      }) as Promise<unknown>,
    Error,
    "STL file not found",
  );
});

Deno.test("STL admission accepts both committed ASCII and declared binary STL sources", async () => {
  await assertAdmittedStlSource("stl-admission-test", CUBE_20MM_STL);

  const binaryStl = await Deno.makeTempFile({
    prefix: "slicer-binary-stl-",
    suffix: ".stl",
  });
  const bytes = new Uint8Array(84 + 50);
  new DataView(bytes.buffer).setUint32(80, 1, true);
  await Deno.writeFile(binaryStl, bytes);
  try {
    await assertAdmittedStlSource("stl-admission-test", binaryStl);
  } finally {
    await Deno.remove(binaryStl).catch(() => {});
  }
});

Deno.test("ZIP signatures cannot collide into binary STL admission or reach the runner", async () => {
  const tool = estimateTool();
  const signatures = [
    [0x50, 0x4b, 0x03, 0x04],
    [0x50, 0x4b, 0x05, 0x06],
    [0x50, 0x4b, 0x07, 0x08],
  ];

  for (const signature of signatures) {
    const renamedProject = await Deno.makeTempFile({
      prefix: "slicer-renamed-project-",
      suffix: ".stl",
    });
    // 84 + one 50-byte triangle = 134 bytes. Before the ZIP guard this
    // intentionally collided with the binary-STL size/count predicate.
    const bytes = new Uint8Array(134);
    bytes.set(signature);
    new DataView(bytes.buffer).setUint32(80, 1, true);
    await Deno.writeFile(renamedProject, bytes);
    try {
      await assertRejects(
        () =>
          tool.handler({
            stl_path: renamedProject,
            profile_ini_path: PROFILE_INI,
          }) as Promise<unknown>,
        InputArtifactError,
        "ZIP/3MF archive signature",
      );
    } finally {
      await Deno.remove(renamedProject).catch(() => {});
    }
  }
});

Deno.test("prusaslicer_estimate_fff refuses .3mf before snapshot or slicer execution", async () => {
  const tool = estimateTool();
  // The path deliberately does not exist. Its typed non-STL refusal proves the
  // handler rejects by contract before it can copy/open the input or spawn a
  // slicer process.
  await assertRejects(
    () =>
      tool.handler({
        stl_path: "/must-not-be-opened/project.3mf",
        profile_ini_path: PROFILE_INI,
      }) as Promise<unknown>,
    InputArtifactError,
    "refused non-STL path before snapshot or slicer execution",
  );
});

Deno.test("prusaslicer_estimate_fff reports profile not found as InputArtifactError", async () => {
  const tool = estimateTool();
  await assertRejects(
    () =>
      tool.handler({
        stl_path: CUBE_20MM_STL,
        profile_ini_path: "/nonexistent/profile.ini",
      }) as Promise<unknown>,
    Error,
    "INI file not found",
  );
});

Deno.test("prusaslicer_estimate_fff rejects non-positive timeout_ms at the handler", async () => {
  const tool = estimateTool();
  for (const timeout_ms of [0, -1, 1.5, Number.NaN, Number.POSITIVE_INFINITY]) {
    await assertRejects(
      () =>
        tool.handler({
          stl_path: CUBE_20MM_STL,
          profile_ini_path: PROFILE_INI,
          timeout_ms,
        }) as Promise<unknown>,
      TypeError,
      "timeout_ms",
    );
  }
});

Deno.test("sliceFff rejects non-positive timeout_ms before spawning", async () => {
  for (const timeoutMs of [0, -1, 1.5]) {
    await assertRejects(
      () =>
        sliceFff({
          stlPath: CUBE_20MM_STL,
          profileIniPath: PROFILE_INI,
          timeoutMs,
        }),
      SlicingError,
      "timeout_ms",
    );
  }
});

// ---------------------------------------------------------------------------
// Native integration tests — require PRUSASLICER_RUN_NATIVE=1 and prusa-slicer
// ---------------------------------------------------------------------------

Deno.test({
  name:
    "prusaslicer_estimate_fff slices a 20mm cube and returns stats matching the committed fixture",
  ignore: !RUN_NATIVE,
  fn: async () => {
    const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
    assert(tool, "tool must exist");

    const result = await tool.handler({
      stl_path: CUBE_20MM_STL,
      profile_ini_path: PROFILE_INI,
    }) as { structuredContent: Record<string, unknown> };

    const sc = result.structuredContent;

    // Reference values (PrusaSlicer 2.9.2, cube_20mm.stl, pla_0.4_0.2.ini):
    //   filament_length_mm  = 1487.15
    //   filament_volume_mm3 = 3580
    //   filament_mass_g     = 4.44
    //   print_time_s        = 1190  (19m 50s)
    assert(
      typeof sc.print_time_s === "number" && sc.print_time_s > 0,
      "print_time_s > 0",
    );
    assert(
      typeof sc.filament_length_mm === "number" && sc.filament_length_mm > 500,
      "filament_length_mm > 500 for 20mm cube",
    );
    assert(
      typeof sc.filament_volume_mm3 === "number" && sc.filament_volume_mm3 > 0,
      "filament_volume_mm3 > 0",
    );
    assert(
      typeof sc.filament_mass_g === "number" && sc.filament_mass_g > 0,
      "filament_mass_g present and positive when density is set",
    );

    // Tolerance ±20% on reference values (printer config may vary).
    assert(
      Math.abs((sc.filament_length_mm as number) - 1487.15) < 1487.15 * 0.2,
      `filament_length_mm out of tolerance: ${sc.filament_length_mm}`,
    );
    assert(
      Math.abs((sc.filament_volume_mm3 as number) - 3580) < 3580 * 0.2,
      `filament_volume_mm3 out of tolerance: ${sc.filament_volume_mm3}`,
    );
    assert(
      Math.abs((sc.filament_mass_g as number) - 4.44) < 4.44 * 0.2,
      `filament_mass_g out of tolerance: ${sc.filament_mass_g}`,
    );

    // G-code hash must be a 64-char hex string.
    assert(
      typeof sc.gcode_sha256 === "string" && (sc.gcode_sha256 as string).length === 64,
      "gcode_sha256 must be a 64-char hex string",
    );

    assertEquals(sc.engine_name, "PrusaSlicer");
    assert(
      typeof sc.engine_version === "string" &&
        /^\d+\.\d+/.test(sc.engine_version as string),
      `engine_version should look like a version, got: ${sc.engine_version}`,
    );
    assert(
      typeof sc.effective_config_sha256 === "string" &&
        (sc.effective_config_sha256 as string).length === 64,
      "effective_config_sha256 must be a 64-char hex string",
    );
    const effectiveConfigSummary = sc.effective_config_summary as Record<
      string,
      unknown
    >;
    assertEquals(
      effectiveConfigSummary.config_sha256,
      sc.effective_config_sha256,
      "effective-config projection must attest the same emitted block",
    );
    const effectiveConfigValues = effectiveConfigSummary.values as Record<
      string,
      unknown
    >;
    assertEquals(effectiveConfigValues.layer_height, "0.2");
    assertEquals(effectiveConfigValues.fill_density, "20%");
    assertEquals(sc.overrides_applied, {});

    // Attestation fields.
    const stlArt = sc.stl_artifact as Record<string, unknown>;
    assert(
      typeof stlArt.sha256 === "string" && (stlArt.sha256 as string).length === 64,
      "stl_artifact.sha256 must be 64-char hex",
    );
    const profArt = sc.profile_artifact as Record<string, unknown>;
    assert(
      typeof profArt.sha256 === "string" && (profArt.sha256 as string).length === 64,
      "profile_artifact.sha256 must be 64-char hex",
    );
  },
});

Deno.test({
  name: "prusaslicer_estimate_fff: filament_mass_g absent when profile has no density",
  ignore: !RUN_NATIVE,
  fn: async () => {
    const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
    assert(tool, "tool must exist");

    // Write a profile without filament_density to a temp file.
    const tmpProfile = await Deno.makeTempFile({
      prefix: "slicer-test-",
      suffix: ".ini",
    });
    await Deno.writeTextFile(
      tmpProfile,
      [
        "printer_technology = FFF",
        "nozzle_diameter = 0.4",
        "layer_height = 0.2",
        "first_layer_height = 0.2",
        "bed_shape = 0x0,250x0,250x210,0x210",
        "filament_diameter = 1.75",
        "temperature = 215",
        "first_layer_temperature = 215",
        "bed_temperature = 60",
        "first_layer_bed_temperature = 60",
        "fill_density = 20%",
        "perimeters = 3",
        "gcode_flavor = marlin",
      ].join("\n"),
    );

    try {
      const result = await tool.handler({
        stl_path: CUBE_20MM_STL,
        profile_ini_path: tmpProfile,
      }) as { structuredContent: Record<string, unknown> };

      // When density is absent: field must be absent (not null, not 0).
      assert(
        !("filament_mass_g" in result.structuredContent),
        "filament_mass_g must be absent (not null) when profile has no density",
      );
    } finally {
      await Deno.remove(tmpProfile).catch(() => {});
    }
  },
});

Deno.test({
  name: "prusaslicer_estimate_fff: layer_height_mm override changes slice result",
  ignore: !RUN_NATIVE,
  fn: async () => {
    const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
    assert(tool, "tool must exist");

    // Baseline at default 0.2mm layer.
    const base = await tool.handler({
      stl_path: CUBE_20MM_STL,
      profile_ini_path: PROFILE_INI,
    }) as { structuredContent: Record<string, unknown> };

    // 0.3mm layer → fewer layers → less filament and less time.
    const override = await tool.handler({
      stl_path: CUBE_20MM_STL,
      profile_ini_path: PROFILE_INI,
      layer_height_mm: 0.3,
    }) as { structuredContent: Record<string, unknown> };

    const baseMm = base.structuredContent.filament_length_mm as number;
    const overrideMm = override.structuredContent.filament_length_mm as number;
    assert(
      overrideMm < baseMm,
      `layer_height_mm=0.3 should use less filament than 0.2: ${overrideMm} < ${baseMm}`,
    );
    assertEquals(base.structuredContent.overrides_applied, {});
    assertEquals(override.structuredContent.overrides_applied, {
      layer_height_mm: 0.3,
    });
    const baseConfigSummary = base.structuredContent.effective_config_summary as Record<
      string,
      unknown
    >;
    const overrideConfigSummary = override.structuredContent
      .effective_config_summary as Record<string, unknown>;
    const baseConfigValues = baseConfigSummary.values as Record<string, unknown>;
    const overrideConfigValues = overrideConfigSummary.values as Record<
      string,
      unknown
    >;
    assertEquals(
      baseConfigValues.layer_height,
      "0.2",
      "the emitted baseline config must preserve the supplied layer height",
    );
    assertEquals(
      overrideConfigValues.layer_height,
      "0.3",
      "the emitted config must record the forwarded layer-height override",
    );
    assertEquals(
      overrideConfigSummary.config_sha256,
      override.structuredContent.effective_config_sha256,
      "the override summary must remain bound to the actual emitted config block",
    );
    assert(
      base.structuredContent.effective_config_sha256 !==
        override.structuredContent.effective_config_sha256,
      "changing layer_height_mm must change the emitted prusaslicer_config hash",
    );
  },
});

Deno.test({
  name:
    "prusaslicer_estimate_fff: filament_density_g_cm3 override provides mass when profile lacks density",
  ignore: !RUN_NATIVE,
  fn: async () => {
    const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
    assert(tool, "tool must exist");

    // Write a profile without filament_density.
    const tmpProfile = await Deno.makeTempFile({
      prefix: "slicer-test-",
      suffix: ".ini",
    });
    await Deno.writeTextFile(
      tmpProfile,
      [
        "printer_technology = FFF",
        "nozzle_diameter = 0.4",
        "layer_height = 0.2",
        "first_layer_height = 0.2",
        "bed_shape = 0x0,250x0,250x210,0x210",
        "filament_diameter = 1.75",
        "temperature = 215",
        "first_layer_temperature = 215",
        "bed_temperature = 60",
        "first_layer_bed_temperature = 60",
        "fill_density = 20%",
        "perimeters = 3",
        "gcode_flavor = marlin",
      ].join("\n"),
    );

    try {
      const result = await tool.handler({
        stl_path: CUBE_20MM_STL,
        profile_ini_path: tmpProfile,
        filament_density_g_cm3: 1.24,
      }) as { structuredContent: Record<string, unknown> };

      assert(
        "filament_mass_g" in result.structuredContent,
        "filament_mass_g must be present when filament_density_g_cm3 override is provided",
      );
      assert(
        typeof result.structuredContent.filament_mass_g === "number" &&
          (result.structuredContent.filament_mass_g as number) > 0,
        "filament_mass_g must be positive",
      );
      assertEquals(result.structuredContent.overrides_applied, {
        filament_density_g_cm3: 1.24,
      });
    } finally {
      await Deno.remove(tmpProfile).catch(() => {});
    }
  },
});

Deno.test({
  name:
    "prusaslicer_estimate_fff slices a 10mm cube (legacy fixture) and returns plausible stats",
  ignore: !RUN_NATIVE,
  fn: async () => {
    const tool = allTools.find((t) => t.name === "prusaslicer_estimate_fff");
    assert(tool, "tool must exist");

    const result = await tool.handler({
      stl_path: CUBE_10MM_STL,
      profile_ini_path: PROFILE_INI,
    }) as { structuredContent: Record<string, unknown> };

    const sc = result.structuredContent;

    // Reference values (PrusaSlicer 2.9.2, cube.stl 10mm, pla_0.4_0.2.ini):
    //   filament_length_mm  ≈ 426.64
    //   filament_volume_mm3 ≈ 1030
    //   filament_mass_g     ≈ 1.27
    //   print_time_s        ≈ 765  (12m 45s)
    assert(
      typeof sc.print_time_s === "number" && sc.print_time_s > 0,
      "print_time_s > 0",
    );
    assert(
      typeof sc.filament_length_mm === "number" && sc.filament_length_mm > 100,
      "filament_length_mm > 100 for 10mm cube",
    );
    // Tolerance ±20%
    assert(
      Math.abs((sc.filament_length_mm as number) - 426.64) < 426.64 * 0.2,
      `filament_length_mm out of tolerance: ${sc.filament_length_mm}`,
    );
  },
});
