; generated by PrusaSlicer 2.9.2 on 2026-08-05 at 00:09:06 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

M190 S60 ; set bed temperature and wait for it to be reached
M104 S215 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S215 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-2 F2400
G92 E0
G1 Z.2 F7800
G1 X110.358 Y90.923
; ... [G-code toolpath omitted for fixture; 8060 lines] ...
; filament used [mm] = 1487.15
; filament used [cm3] = 3.58
; filament used [g] = 4.44
; total filament used [g] = 4.44
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 19m 50s
; estimated printing time (silent mode) = 20m 40s
; estimated first layer printing time (normal mode) = 46s
; estimated first layer printing time (silent mode) = 46s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; ...
; prusaslicer_config = end
